grammar;

use crate::parser::ast::{Expr, FuncCall, FuncLiteral, Include, Module, Statement, VarDecl};
use crate::parser::ast::Operator as Op;
use crate::parser::lalrpop::{as_args, as_formals, as_symbol, Param, sequence};
use crate::errors::ParserError;
use crate::lexer::source_loc::MiniLoc;
use crate::lexer::token::{Token, TokenType};

extern {
  type Location = MiniLoc;
  type Error    = ParserError;

  enum Token {
    "identifier" => Token { token_type: TokenType::Identifier(String), .. },
    "include"    => Token { token_type: TokenType::Include           , .. },
    "number"     => Token { token_type: TokenType::Number(f64)       , .. },
    "string"     => Token { token_type: TokenType::String(String)    , .. },
    ":"          => Token { token_type: TokenType::Colon             , .. },
    ","          => Token { token_type: TokenType::Comma             , .. },
    "/"          => Token { token_type: TokenType::Divide            , .. },
    "="          => Token { token_type: TokenType::Equals            , .. },
    ">"          => Token { token_type: TokenType::GreaterThan       , .. },
    ">="         => Token { token_type: TokenType::GreaterThanEquals , .. },
    "{"          => Token { token_type: TokenType::LeftBrace         , .. },
    "["          => Token { token_type: TokenType::LeftBracket       , .. },
    "("          => Token { token_type: TokenType::LeftParen         , .. },
    "<"          => Token { token_type: TokenType::LessThan          , .. },
    "<="         => Token { token_type: TokenType::LessThanEquals    , .. },
    "-"          => Token { token_type: TokenType::Minus             , .. },
    "*"          => Token { token_type: TokenType::Multiply          , .. },
    "+"          => Token { token_type: TokenType::Plus              , .. },
    "}"          => Token { token_type: TokenType::RightBrace        , .. },
    "]"          => Token { token_type: TokenType::RightBracket      , .. },
    ")"          => Token { token_type: TokenType::RightParen        , .. },
  }
}

pub Module: Module = {
  <includes: Include*> <statements: Statement*> => Module { includes, statements },
}

pub Statement: Statement = {
  <fn_call: FuncCall>                    => Statement::FunctionCall(Box::new(fn_call)),
  <ident: "identifier"> "=" <expr: Expr> => Statement::VariableDecl(VarDecl { name: as_symbol(&ident, "var name"), init: expr }),
  <ident: "identifier"> "(" <params: Params> ")" "=" "{" <body: Statement*> "}" =>? {
    let symbol = as_symbol(&ident, "function name");
    Ok(Statement::VariableDecl(
      VarDecl { name: symbol.clone()
              , init: Expr::Function {
                        value: FuncLiteral { name: symbol, formals: as_formals(params)?, body },
                        token: ident
                      }
              }
    ))
  }
};

Include: Include = {
  "include" "(" <token: "string"> ")" =>
    match &token.token_type {
      TokenType::String(path) => Include { path: path.to_string() },
      x                       => panic!("Impossible `include` path: {x:?}")
    },
};

Expr: Expr = {
  Comparison
};

Comparison: Expr = {
  <lhs: AddSub> <token: ">="> <rhs: AddSub> => Expr::Op { left: Box::new(lhs), operator: Op::GreaterOrEquals, right: Box::new(rhs), token },
  <lhs: AddSub> <token:  ">"> <rhs: AddSub> => Expr::Op { left: Box::new(lhs), operator: Op::GreaterThan    , right: Box::new(rhs), token },
  <lhs: AddSub> <token: "<="> <rhs: AddSub> => Expr::Op { left: Box::new(lhs), operator: Op::LessOrEquals   , right: Box::new(rhs), token },
  <lhs: AddSub> <token:  "<"> <rhs: AddSub> => Expr::Op { left: Box::new(lhs), operator: Op::LessThan       , right: Box::new(rhs), token },
  AddSub,
};

AddSub: Expr = {
  <lhs: AddSub> <token: "+"> <rhs: MulDiv> => Expr::Op { left: Box::new(lhs), operator: Op::Plus , right: Box::new(rhs), token },
  <lhs: AddSub> <token: "-"> <rhs: MulDiv> => Expr::Op { left: Box::new(lhs), operator: Op::Minus, right: Box::new(rhs), token },
  MulDiv,
};

MulDiv: Expr = {
  <lhs: MulDiv> <token: "*"> <rhs: Unary> => Expr::Op { left: Box::new(lhs), operator: Op::Times , right: Box::new(rhs), token },
  <lhs: MulDiv> <token: "/"> <rhs: Unary> => Expr::Op { left: Box::new(lhs), operator: Op::Divide, right: Box::new(rhs), token },
  Unary,
};

Unary: Expr = {
  <token: "-"> <expr: Unary> => Expr::Negated { value: Box::new(expr), token },
  FnCall,
};

FnCall: Expr = {
  <call: FuncCall> => {
    let token = call.func.token.clone();
    Expr::Call { call, token }
  },
  Primary,
};

FuncCall: FuncCall = {
  <ident: "identifier"> "(" <params: Params> ")" =>?
    Ok(FuncCall { func: as_symbol(&ident, "function name"), args: as_args(params)? }),
}

Params: Vec<Param> = {
  => vec![],

  <head: Param> <tail: ("," <Param>)* > => sequence(head, tail),
};

Param: Param = {
  <ident: "identifier"> <value: (":" <Expr>)?> => Param { symbol: as_symbol(&ident, "argument"), value_option: value },
}

Primary: Expr = {
  <token: "["> <values: ExprSeq> "]" => Expr::List { values, token },

  <token: "("> <expr: Expr> ")" => Expr::Grouping { value: Box::new(expr), token },

  <token: "identifier"> => Expr::LValue { name: as_symbol(&token, "identifier"), token },

  <token: "number"> =>
    match token.token_type {
      TokenType::Number(value) => Expr::Number { value, token },
      x                        => panic!("Impossible number: {x:?}")
    },

  <token: "string"> =>
    match &token.token_type {
      TokenType::String(value) => Expr::String { value: value.to_string(), token },
      x                        => panic!("Impossible string: {x:?}")
    },
};

ExprSeq: Vec<Expr> = {
  => vec![],

  <head: Expr> <tail: ("," <Expr>)* > => sequence(head, tail),
};
